trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

jobs:
- job: DownloadGitHubReleases
  steps:
  - powershell: |
      # Define variables
      $githubRepoOwner = "Marimuthukumaran"
      $githubRepoName = "SampleJarREPO"
      $githubToken = "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"  # Create a GitHub token with 'repo' scope

      # Get the latest release information
      $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/$githubRepoOwner/$githubRepoName/releases/latest" -Headers @{Authorization = "token $githubToken"}

      # Extract the download URL and asset name
      $downloadUrl = $latestRelease.assets[0].browser_download_url
      $assetName = $latestRelease.assets[0].name

      # Download the release asset
      Invoke-WebRequest -Uri $downloadUrl -OutFile $assetName

    displayName: 'Download GitHub Release Asset'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)'
      artifactName: 'GitHubReleaseArtifacts'
    displayName: 'Publish Artifacts'
