trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    githubToken="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"
    repoOwner="Marimuthukumaran"
    repoName="SampleJarREPO"
    releaseId="101"

    url="https://api.github.com/repos/$repoOwner/$repoName/releases"
    headers="Authorization: Bearer $githubToken"

    assets=$(curl -s -H "$headers" "$url")
    echo "$assets"
  displayName: 'List GitHub Release Assets'

