trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

jobs:
- job: DownloadGitHubRelease
  steps:
  - powershell: |
      $downloadUrl = "https://github.com/Marimuthukumaran/SampleJarREPO/releases/tag/101.zip"
      $outputPath = "$(System.DefaultWorkingDirectory)\release.zip"

      # Download the release ZIP file
      Invoke-WebRequest -Uri $downloadUrl -OutFile $outputPath

    displayName: 'Download GitHub Release'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)'
      artifactName: 'GitHubReleaseArtifacts'
    displayName: 'Publish Artifacts'
