trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    githubToken="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"
    repoOwner="Marimuthukumaran"
    repoName="SampleJarREPO"
    releaseTag="101"

    # GitHub API endpoint for the release
    url="https://api.github.com/repos/$repoOwner/$repoName/releases/tags/$releaseTag"

    # Get the download URL for the zipball from the GitHub API
    zipballUrl=$(curl -s "$url" | jq -r '.zipball_url')

    # Specify the local filename for the downloaded zip file
    localZipFile="release_$releaseTag.zip"

    # Download the zipball using curl
    curl -L -o "$localZipFile" "$zipballUrl"

    # Print a message indicating the download is complete
    echo "Release zip file downloaded: $localZipFile"

  displayName: 'List GitHub Release Assets'

