# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: CheckReleasepushtoFeeds
  # timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: DownloadGitHubRelease@0
      inputs:
        connection: 'Marimuthukumaran'
        userRepository: 'Marimuthukumaran/SampleJarREPO'
        defaultVersionType: 'specificTag'
        version: '135238802'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '**/*.zip'
        destinationFolder: '$(System.ArtifactsDirectory)'
        cleanDestinationFolder: true
        overwriteExistingFiles: false
    - task: Maven@4
      inputs:
        mavenPomFile: '$(System.ArtifactsDirectory)/pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        goals: 'package'