trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    displayName: Dowload and unzip the release file
    inputs:
      targetType: 'inline'
      script: |
        githubToken="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"
        repoOwner="Marimuthukumaran"
        repoName="SampleJarREPO"
        releaseId="105"
        url="https://github.com/$repoOwner/$repoName/archive/refs/tags/$releaseId.zip"
            localZipFile="SampleJarREPO-$releaseId.zip"
            extractDir="extracted_files"
        
            # Download the zip file using curl with follow redirects
            response=$(curl -w "%{http_code}" -L -H "Authorization: Bearer $githubToken" -s -o "$localZipFile" "$url" | tr -d '\0')
        
            http_status="${response: -3}"  # Extract the last 3 characters (HTTP status code)
        
            # Check if http_status is a valid integer
            if [[ "$http_status" =~ ^[0-9]+$ ]]; then
                if [ "$http_status" -eq 200 ]; then
                    echo "Zip file downloaded successfully."
        
                    # Create a new directory for extraction
                    mkdir -p "$extractDir"
        
                    # Unzip the downloaded file into the new directory
                    unzip -q "$localZipFile" -d "$extractDir"
        
                    # List all contents recursively
                    echo "Contents of $extractDir:"
                    find "$extractDir"
                    ls
                    cd extracted_files/SampleJarREPO-105
                    ls
                else
                    echo "Error: Failed to download the zip file. HTTP Status Code: $http_status"
                    echo "Full Response: $response"
                fi
            else
                echo "Error: Unable to extract valid HTTP status code from the response."
                echo "Full Response: $response"
            fi
  
  - task: Maven@4
    displayName: Build mainSuite
    inputs:
      mavenPomFile: '$(System.DefaultWorkingDirectory)/extracted_files/SampleJarREPO-105/pom.xml'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: true
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      goals: 'deploy'
      # options: '-Dmaven.test.failure.ignore=true'